version: "3"
 
services:
 wordpress:
   container_name: wordpress
   depends_on:
     - db
   image: wordpress
   links:
     - wordpress_db:mysql
   ports:
     - 8080:80
 db:
   container_name: database
   image: mariadb
   environment:
     WORDPRESS_DB_HOST: db:3306
     MYSQL_ROOT_PASSWORD: 123456789
 phpmyadmin:
   container_name: phpmyadmin
   depends_on:
     - db
   image: corbinu/docker-phpmyadmin
   links:
     - db:mysql
   ports:
     - 8181:80
   environment:
     PMA_HOST: db
     MYSQL_USERNAME: root
     MYSQL_ROOT_PASSWORD: 123456789